
[tool.pytest.ini_options]
pythonpath = ["src/"]
testpaths = "tests"

[tool.bandit]
exclude_dirs = ["tests"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "S", "C90", "B", "UP", "ANN", "N"]

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S", "ANN", "N"]

[tool.ty.src]
include = ["src", "tests"]

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cactus_juice"
description = "CSIP-Aus to OCPP demonstration"
requires-python = ">=3.13"
dynamic = ["version"]
dependencies = [
    "pymodbus[serial]",
    "fastapi",
    "pydantic-settings",
    "sqlalchemy",
    "asyncpg",
    
]

[project.optional-dependencies]
dev = ["alembic", "bandit", "ty", "ruff", "codespell", "coverage", "pytest-cov", "python-dotenv[cli]"]
test = ["alembic", "pytest", "pytest-xdist", "pytest-postgresql", "pytest-asyncio", "assertical", "freezegun", "psycopg"]

[tool.setuptools.package-data]
"cactus_juice" = ["py.typed"]
