#!/bin/bash

#
# create-cert.sh
#
# Creates IEEE 2030.5 signing chains following the CACTUS certificate profiles
# (adapted from the National Energy PKI / NEPKI "DEVICE MANUFACTURER" and
# "OEM AGGREGATOR & DNSP" hierarchy profiles).
#
# Two hierarchies are supported, both sharing a common SERCA root:
#
#   device      SERCA -> MCA            -> MICA            -> device End-Entity
#   dnsp        SERCA -> Services PCA   -> DNSP ICA        -> services End-Entity
#   aggregator  SERCA -> Services PCA   -> Aggregator ICA  -> services End-Entity
#
# Notes on this implementation:
#   * "NEPKI" / "National Energy PKI Limited." identities are adapted to CACTUS
#     (see ORG_NAME / ORG_COUNTRY below).
#   * CRL is NOT supported: no CRLDistributionPoints extensions are emitted.
#     (cRLSign is still asserted in CA keyUsage, matching the source profiles -
#      flip CA_KEY_USAGE below if you want it removed too.)
#   * OCSP/AIA on End-Entity certs is driven by OCSP_URL / CA_ISSUERS_URL below.
#     Leave OCSP_URL blank to omit the AuthorityInfoAccess extension entirely.
#

#
# Constants
#

OID_2030_5="1.3.6.1.4.1.40732"         # OID base for IEEE 2030 (section 6.11.7.1 in IEEE2030.5 2018)
OID_DEV="$OID_2030_5.1"                # OID FOR "DEVICE TYPES" (SECTION 6.11.7.2 IN IEEE2030.5 2018)
OID_DEV_GENERIC="$OID_DEV.1"           # USED FOR MOST DEVICES
OID_DEV_MOBILE="$OID_DEV.2"            # USED IN ADDITION TO "GENERIC DEVICE TYPE" TO IDENTIFY "MOBILE" IEEE 2030.5 ENTITIES
OID_DEV_POST_MANUFACTURE="$OID_DEV.3"  # USED IN DEVICE CERTS ISSUED POST-MANUFACTURE

OID_POLICY="$OID_2030_5.2"                    # OID FOR 2030.5 POLICY ASSIGNMENTS (SECTION 6.11.7.3 IN IEEE2030.5 2018)
OID_2030_5_POLICY_TEST="$OID_POLICY.1"        # MUST BE INCLUDED IN TEST CERTIFICATES
OID_2030_5_POLICY_SELFSIGN="$OID_POLICY.2"    # MUST BE INCLUDED IN IEEE 2030.5 SELF-SIGNED CERTIFICATES
OID_2030_5_POLICY_COMMERCIAL="$OID_POLICY.3"  # MUST BE INCLUDED IN COMMERCIAL CERTIFICATES (po-service-provider)
OID_2030_5_POLICY_BULK="$OID_POLICY.4"        # MUST BE INCLUDED IN BULK-ISSUED CERTIFICATES (PRIV. KEY GENERATED BY CA, NOT BY DEVICE)

OID_2030_5_ID_ON_HARDWARE_MODULE_NAME="1.3.6.1.5.5.7.8.4"

OID_X509_V3_ANY_POLICY="2.5.29.32.0"

#
# CACTUS site configuration
#

ORG_NAME="CACTUS"   # replaces NEPKI "National Energy PKI Limited."
ORG_COUNTRY="AU"

# Manufacturer/model OID used in the End-Entity SubjectAltName otherName (hwType).
# PEN-based; UPDATE per manufacturer/model. (1.3.6.1.4.1.28547 is the ANU PEN.)
HW_TYPE_OID="1.3.6.1.4.1.28547.1.1.1"

# Authority Information Access (OCSP) for End-Entity certs.
# Leave OCSP_URL blank to omit the AIA extension entirely.
OCSP_URL=""        # UPDATE to the real OCSP responder URL (or blank to omit AIA)
CA_ISSUERS_URL=""  # UPDATE to the real CA-Issuers URL (used only if OCSP_URL set)

# keyUsage asserted on all CA certificates. Source profiles set keyCertSign + cRLSign.
CA_KEY_USAGE="critical, keyCertSign, cRLSign"

# Validity periods (years) per the profiles.
SERCA_YEARS=35
L2_YEARS=25     # MCA / Services PCA
L3_YEARS=15     # MICA / DNSP ICA / Aggregator ICA
DEVICE_EE_YEARS=5
SERVICES_EE_YEARS=2

# Policy OID sets (comma separated) per the profiles.
CA_POLICIES="$OID_DEV_GENERIC,$OID_DEV_MOBILE,$OID_DEV_POST_MANUFACTURE"
# Device EE profile lists the full menu (1.1-1.3, 2.1-2.4); this is a sensible
# post-manufacture *test* default. Adjust as required.
DEVICE_EE_POLICIES="$OID_DEV_GENERIC,$OID_DEV_POST_MANUFACTURE,$OID_2030_5_POLICY_TEST"
# Services EE profile mandates dev-generic + po-service-provider.
SERVICES_EE_POLICIES="$OID_DEV_GENERIC,$OID_2030_5_POLICY_COMMERCIAL"

#
# Utility Functions
#

usage() {
    echo "create-cert PROFILE SERCA_ID SERCA_SERIAL [CHAIN_ID] [CHAIN_SERIAL] [EE_NAME] [EE_SERIAL] [EE_DNS]"
    echo ""
    echo "Creates the specified chain of certificate(s) and keys up to the last specified parameter."
    echo "Will NOT replace existing certs (you will need to manually delete those to force a refresh)"
    echo ""
    echo "PROFILE      = Mandatory hierarchy type:"
    echo "                 device     -> SERCA -> MCA           -> MICA           -> device End-Entity"
    echo "                 dnsp       -> SERCA -> Services PCA  -> DNSP ICA       -> services End-Entity"
    echo "                 aggregator -> SERCA -> Services PCA  -> Aggregator ICA -> services End-Entity"
    echo "SERCA_ID     = Mandatory unique id of the root SERCA (also the folder name)"
    echo "SERCA_SERIAL = Mandatory serialNumber value placed in the SERCA DN - informational"
    echo "CHAIN_ID     = Optional unique id for the L2/L3 CA chain underneath SERCA_ID (folder name)"
    echo "CHAIN_SERIAL = Optional integer serial for the L2/L3 chain certificates"
    echo "EE_NAME      = Optional End-Entity name."
    echo "                 device profile     -> used as the hwSerialNum seed (no DNS, empty subject)"
    echo "                 dnsp/aggregator    -> used as the Subject CN and the SAN DNS name"
    echo "EE_SERIAL    = Optional integer serial for the End-Entity certificate"
    echo "EE_DNS       = Optional DNS name placed in the SAN of a services (dnsp/aggregator) cert."
    echo "                 Defaults to EE_NAME. May be a different domain or a wildcard, e.g."
    echo "                 '*.cactus-dev.cecs.anu.edu.au'. Ignored for the 'device' profile (no DNS SAN)."
    echo ""
    echo "NOTE: PROFILE selects which set of CACTUS IEEE 2030.5 profiles to apply."
    echo "NOTE: All id/name parameters form parts of a file/folder name."
    exit 1
}

years_to_days() {
    # Approximate calendar years -> days (accounts for leap days). Adequate for cert validity.
    echo $(( $1 * 365 + $1 / 4 ))
}

generate_key() {
    local key_file=$1
    openssl ecparam -name prime256v1 -genkey -noout -out "$key_file" || { echo "Failure to generate key"; exit 1; }
    chmod 400 "$key_file"
}

calculate_key_identifier() {
    local key_file=$1
    local pub_file=$2

    # Generate subjectKeyIdentifier from the public key (Method is referenced in 2030.5 - Section 6.11.6)
    # From - 4.2.1.2 of IETF RFC 5280
    # Method requires the least significant 60 bits of the SHA-1 public key (or last 15 hex chars)
    openssl ec -in "$key_file" -pubout -outform DER -out "$pub_file" 2>/dev/null || { echo "Failure to extract public key"; exit 1; }
    # openssl-only hex digest (portable; no xxd dependency). Produces identical output.
    local sha1_hash=$(openssl dgst -sha1 "$pub_file" | awk '{print $NF}')
    echo "4${sha1_hash:(-15)}"
    return 0
}

# create_ca <key_file> <cert_file> <cfg_file> <pub_file> <subject> <pathlen|none>
#           <policies> <validity_days> <signer_cert|SELF> <signer_key> <cert_serial>
create_ca() {
    local key_file=$1 cert_file=$2 cfg_file=$3 pub_file=$4
    local subject=$5 pathlen=$6 policies=$7 days=$8
    local signer_cert=$9 signer_key=${10} cert_serial=${11}
    local csr_file="${cfg_file}.csr"

    generate_key "$key_file"
    local kid
    kid=$(calculate_key_identifier "$key_file" "$pub_file")

    local bc="critical,CA:true"
    [[ "$pathlen" != "none" ]] && bc="critical,CA:true,pathlen:$pathlen"

    local aki_line=""
    [[ "$signer_cert" != "SELF" ]] && aki_line="authorityKeyIdentifier = keyid:always"

    # NOTE: extensions are applied at signing time (openssl x509 -extfile -extensions),
    # NOT via req_extensions - authorityKeyIdentifier=keyid:always can only resolve the
    # issuer's key id once the -CA issuer is present (i.e. during signing, not CSR creation).
    cat > "$cfg_file" <<EOL
[ req ]
prompt = no

[ ca_ext ]
subjectKeyIdentifier   = $kid
basicConstraints       = $bc
keyUsage               = $CA_KEY_USAGE
certificatePolicies    = critical,$policies
$aki_line
EOL

    openssl req -new -key "$key_file" -out "$csr_file" -config "$cfg_file" -subj "$subject" \
        || { echo "Failure to generate CSR"; exit 1; }

    if [[ "$signer_cert" == "SELF" ]]; then
        openssl x509 -req -in "$csr_file" -signkey "$key_file" -out "$cert_file" \
            -days "$days" -extfile "$cfg_file" -extensions ca_ext -sha256 \
            || { echo "Failure to generate CERT"; exit 1; }
    else
        openssl x509 -req -in "$csr_file" -CA "$signer_cert" -CAkey "$signer_key" \
            -set_serial "$cert_serial" -out "$cert_file" \
            -days "$days" -extfile "$cfg_file" -extensions ca_ext -sha256 \
            || { echo "Failure to generate CERT"; exit 1; }
    fi
    rm -f "$csr_file"
}

# Builds the AuthorityInfoAccess config line (empty if OCSP_URL is unset).
aia_line() {
    [[ -z "$OCSP_URL" ]] && { echo ""; return; }
    local line="authorityInfoAccess    = OCSP;URI:$OCSP_URL"
    [[ -n "$CA_ISSUERS_URL" ]] && line="$line, caIssuers;URI:$CA_ISSUERS_URL"
    echo "$line"
}

#
# Parse parameters
#
PROFILE="$1"
SERCA_ID="$2"
SERCA_SERIAL="$3"
CHAIN_ID="$4"
CHAIN_SERIAL="$5"
EE_NAME="$6"
EE_SERIAL="$7"
EE_DNS="$8"
[[ -z "$EE_DNS" ]] && EE_DNS="$EE_NAME"   # default the SAN DNS name to EE_NAME

case "$PROFILE" in
    device)
        L2_LABEL="MCA";  L3_LABEL="MICA"
        L2_CN="IEEE 2030.5 MCA"
        L3_CN="IEEE 2030.5 MICA"
        EE_KIND="device"
        ;;
    dnsp)
        L2_LABEL="pca";  L3_LABEL="ica"
        L2_CN="$ORG_NAME Services PCA"
        L3_CN="$ORG_NAME DNSP ICA"
        EE_KIND="services"
        ;;
    aggregator)
        L2_LABEL="pca";  L3_LABEL="ica"
        L2_CN="$ORG_NAME Services PCA"
        L3_CN="$ORG_NAME Aggregator ICA"
        EE_KIND="services"
        ;;
    "")
        echo "ERROR - No PROFILE specified."
        echo ""
        usage
        ;;
    *)
        echo "ERROR - Unknown PROFILE '$PROFILE' (expected: device | dnsp | aggregator)."
        echo ""
        usage
        ;;
esac

if [[ -z "${SERCA_ID}" ]]; then
    echo "ERROR - No SERCA_ID specified."
    echo ""
    usage
fi

if [[ -z "${SERCA_SERIAL}" ]]; then
    echo "ERROR - No SERCA_SERIAL specified."
    echo ""
    usage
fi

if [[ -n "${CHAIN_ID}" && -z "${CHAIN_SERIAL}" ]]; then
    echo "ERROR - CHAIN_ID was specified but CHAIN_SERIAL was left blank."
    echo ""
    usage
fi

if [[ -n "${EE_NAME}" && -z "${EE_SERIAL}" ]]; then
    echo "ERROR - EE_NAME was specified but EE_SERIAL was left blank."
    echo ""
    usage
fi

#
# SERCA (Root CA) - common to all profiles
#
SERCA_DIR="./$SERCA_ID"
SERCA_KEY_FILE="$SERCA_DIR/serca.key.pem"
SERCA_CERT_FILE="$SERCA_DIR/serca.cert.pem"
SERCA_PUB_FILE="$SERCA_DIR/.pub.der"
SERCA_CFG_FILE="$SERCA_DIR/.openssl.cnf"

if [ ! -f "$SERCA_KEY_FILE" ]; then
    echo "Creating SERCA key/cert at '$SERCA_DIR/'"
    mkdir -p "$SERCA_DIR" || exit 1

    create_ca "$SERCA_KEY_FILE" "$SERCA_CERT_FILE" "$SERCA_CFG_FILE" "$SERCA_PUB_FILE" \
        "/C=$ORG_COUNTRY/O=$ORG_NAME/CN=IEEE 2030.5 Root/serialNumber=$SERCA_SERIAL" \
        "none" "$OID_X509_V3_ANY_POLICY" "$(years_to_days $SERCA_YEARS)" \
        "SELF" "" ""

    echo "Generated: $SERCA_KEY_FILE"
    echo "Generated: $SERCA_CERT_FILE"
else
    echo "SERCA key '$SERCA_KEY_FILE' already exists in '$SERCA_DIR/'. Skipping SERCA generation."
fi

if [[ -z "$CHAIN_ID" ]]; then
    echo "Done."
    exit 0
fi

#
# Level 2 CA  (device: MCA  |  services: Services PCA)
#
CHAIN_DIR="./$CHAIN_ID"
L2_KEY_FILE="$CHAIN_DIR/$L2_LABEL.key.pem"
L2_CERT_FILE="$CHAIN_DIR/$L2_LABEL.cert.pem"
L2_PUB_FILE="$CHAIN_DIR/.$L2_LABEL.pub.der"
L2_CFG_FILE="$CHAIN_DIR/.$L2_LABEL.openssl.cnf"

if [ ! -f "$L2_KEY_FILE" ]; then
    echo "Creating $L2_LABEL key/cert at '$CHAIN_DIR/'"
    mkdir -p "$CHAIN_DIR" || exit 1

    create_ca "$L2_KEY_FILE" "$L2_CERT_FILE" "$L2_CFG_FILE" "$L2_PUB_FILE" \
        "/C=$ORG_COUNTRY/O=$ORG_NAME/CN=$L2_CN/serialNumber=$CHAIN_SERIAL" \
        "1" "$CA_POLICIES" "$(years_to_days $L2_YEARS)" \
        "$SERCA_CERT_FILE" "$SERCA_KEY_FILE" "$CHAIN_SERIAL"

    echo "Generated: $L2_KEY_FILE"
    echo "Generated: $L2_CERT_FILE"
else
    echo "$L2_LABEL key '$L2_KEY_FILE' already exists in '$CHAIN_DIR/'. Skipping $L2_LABEL generation."
fi

#
# Level 3 CA  (device: MICA  |  services: DNSP/Aggregator ICA)
#
L3_KEY_FILE="$CHAIN_DIR/$L3_LABEL.key.pem"
L3_CERT_FILE="$CHAIN_DIR/$L3_LABEL.cert.pem"
L3_PUB_FILE="$CHAIN_DIR/.$L3_LABEL.pub.der"
L3_CFG_FILE="$CHAIN_DIR/.$L3_LABEL.openssl.cnf"

if [ ! -f "$L3_KEY_FILE" ]; then
    echo "Creating $L3_LABEL key/cert at '$CHAIN_DIR/'"
    mkdir -p "$CHAIN_DIR" || exit 1

    create_ca "$L3_KEY_FILE" "$L3_CERT_FILE" "$L3_CFG_FILE" "$L3_PUB_FILE" \
        "/C=$ORG_COUNTRY/O=$ORG_NAME/CN=$L3_CN/serialNumber=$CHAIN_SERIAL" \
        "0" "$CA_POLICIES" "$(years_to_days $L3_YEARS)" \
        "$L2_CERT_FILE" "$L2_KEY_FILE" "$CHAIN_SERIAL"

    echo "Generated: $L3_KEY_FILE"
    echo "Generated: $L3_CERT_FILE"
else
    echo "$L3_LABEL key '$L3_KEY_FILE' already exists in '$CHAIN_DIR/'. Skipping $L3_LABEL generation."
fi

if [[ -z "$EE_NAME" ]]; then
    echo "Done."
    exit 0
fi

#
# End-Entity certificate
#
EE_DIR="./$EE_NAME"
EE_KEY_FILE="$EE_DIR/$EE_NAME.key.pem"
EE_CERT_FILE="$EE_DIR/$EE_NAME.cert.pem"
EE_BUNDLE_FILE="$EE_DIR/$EE_NAME.fullchain.pem"
EE_CSR_FILE="$EE_DIR/.csr.pem"
EE_PUB_FILE="$EE_DIR/.pub.der"
EE_CFG_FILE="$EE_DIR/.openssl.cnf"

if [ ! -f "$EE_KEY_FILE" ]; then
    echo "Creating End-Entity key/cert at '$EE_DIR/'"
    mkdir -p "$EE_DIR" || exit 1

    generate_key "$EE_KEY_FILE"
    KEY_IDENTIFIER=$(calculate_key_identifier "$EE_KEY_FILE" "$EE_PUB_FILE")
    AIA_LINE=$(aia_line)

    if [[ "$EE_KIND" == "device" ]]; then
        # Device End-Entity: empty Subject, CRITICAL SAN (otherName only), no DNS, no EKU.
        cat > "$EE_CFG_FILE" <<EOL
[ req ]
distinguished_name = empty_distinguished_name
prompt = no

[ empty_distinguished_name ]

[ ee ]
subjectKeyIdentifier   = $KEY_IDENTIFIER
keyUsage               = critical, digitalSignature, keyAgreement
certificatePolicies    = critical,$DEVICE_EE_POLICIES
subjectAltName         = critical,@alt_names
authorityKeyIdentifier = keyid:always
$AIA_LINE

[ HardwareModuleName ]
hwType=OID:$HW_TYPE_OID
hwSerialNum=OCT:cactus-$EE_NAME

[ alt_names ]
otherName.1 = $OID_2030_5_ID_ON_HARDWARE_MODULE_NAME;SEQ:HardwareModuleName
EOL
        openssl req -new -key "$EE_KEY_FILE" -out "$EE_CSR_FILE" -config "$EE_CFG_FILE" -subj "/" \
            || { echo "Failure to generate CSR"; exit 1; }
    else
        # Services End-Entity: Subject CN set, NON-critical SAN (otherName + DNS), EKU client+server.
        cat > "$EE_CFG_FILE" <<EOL
[ req ]
distinguished_name = empty_distinguished_name
prompt = no

[ empty_distinguished_name ]

[ ee ]
subjectKeyIdentifier   = $KEY_IDENTIFIER
keyUsage               = critical, digitalSignature, keyAgreement
extendedKeyUsage       = clientAuth, serverAuth
certificatePolicies    = critical,$SERVICES_EE_POLICIES
subjectAltName         = @alt_names
authorityKeyIdentifier = keyid:always
$AIA_LINE

[ HardwareModuleName ]
hwType=OID:$HW_TYPE_OID
hwSerialNum=OCT:cactus-$EE_NAME

[ alt_names ]
otherName.1 = $OID_2030_5_ID_ON_HARDWARE_MODULE_NAME;SEQ:HardwareModuleName
DNS.1 = $EE_DNS
EOL
        openssl req -new -key "$EE_KEY_FILE" -out "$EE_CSR_FILE" -config "$EE_CFG_FILE" \
            -subj "/C=$ORG_COUNTRY/O=$ORG_NAME/CN=$EE_NAME" \
            || { echo "Failure to generate CSR"; exit 1; }
    fi

    if [[ "$EE_KIND" == "device" ]]; then
        EE_DAYS=$(years_to_days $DEVICE_EE_YEARS)
    else
        EE_DAYS=$(years_to_days $SERVICES_EE_YEARS)
    fi

    openssl x509 -req -in "$EE_CSR_FILE" -CA "$L3_CERT_FILE" -CAkey "$L3_KEY_FILE" \
        -set_serial "$EE_SERIAL" -out "$EE_CERT_FILE" \
        -days "$EE_DAYS" -extfile "$EE_CFG_FILE" -extensions ee -sha256 \
        || { echo "Failure to generate CERT"; exit 1; }

    cat "$EE_CERT_FILE" "$L3_CERT_FILE" "$L2_CERT_FILE" > "$EE_BUNDLE_FILE"
    rm -f "$EE_CSR_FILE"

    echo "Generated: $EE_KEY_FILE"
    echo "Generated: $EE_CERT_FILE"
    echo "Generated: $EE_BUNDLE_FILE"
else
    echo "End-Entity key '$EE_KEY_FILE' already exists in '$EE_DIR/'. Skipping End-Entity cert generation."
fi

echo "Done."
exit 0