"""init

Revision ID: 2314e3ad8f1e
Revises:
Create Date: 2026-09-08 16:47:09.115977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2314e3ad8f1e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "csipaus_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_aggregator", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column("certificate_pem", sa.LargeBinary(), nullable=True),
        sa.Column("key_pem", sa.LargeBinary(), nullable=True),
        sa.Column("nmi", sa.String(), nullable=True),
        sa.Column("client_pen", sa.INTEGER(), nullable=True),
        sa.Column("dcap_uri", sa.String(), nullable=True),
        sa.Column("serca_pem", sa.LargeBinary(), nullable=True),
        sa.Column("verify_hostname", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column("verify_ssl", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_csipaus_config_created_at"), "csipaus_config", ["created_at"], unique=False)
    op.create_table(
        "csipaus_control",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("primacy", sa.INTEGER(), nullable=False),
        sa.Column("mrid", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.INTEGER(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            sa.Computed(
                "(started_at AT TIME ZONE 'UTC' + duration_seconds * interval '1 second') AT TIME ZONE 'UTC'",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply_to", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ramp_time_seconds", sa.Integer(), nullable=True),
        sa.Column("connect", sa.Boolean(), nullable=True),
        sa.Column("energize", sa.Boolean(), nullable=True),
        sa.Column("import_limit_watts", sa.Integer(), nullable=True),
        sa.Column("export_limit_watts", sa.Integer(), nullable=True),
        sa.Column("load_limit_watts", sa.Integer(), nullable=True),
        sa.Column("generation_limit_watts", sa.Integer(), nullable=True),
        sa.Column("storage_target_watts", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mrid"),
    )
    op.create_index(op.f("ix_csipaus_control_finished_at"), "csipaus_control", ["finished_at"], unique=False)
    op.create_table(
        "csipaus_default",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "active_range",
            postgresql.TSTZRANGE(),
            sa.Computed("tstzrange(started_at, finished_at, '[)')", persisted=True),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ramp_percent_max_second_hundredths", sa.Integer(), nullable=True),
        sa.Column("connect", sa.Boolean(), nullable=True),
        sa.Column("energize", sa.Boolean(), nullable=True),
        sa.Column("import_limit_watts", sa.Integer(), nullable=True),
        sa.Column("export_limit_watts", sa.Integer(), nullable=True),
        sa.Column("load_limit_watts", sa.Integer(), nullable=True),
        sa.Column("generation_limit_watts", sa.Integer(), nullable=True),
        sa.Column("storage_target_watts", sa.Integer(), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("active_range"), "&&"), using="gist", name="excl_csipaus_default_active_range_overlap"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "csipaus_dynamic_price",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("primacy", sa.INTEGER(), nullable=False),
        sa.Column("mrid", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.INTEGER(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            sa.Computed(
                "(started_at AT TIME ZONE 'UTC' + duration_seconds * interval '1 second') AT TIME ZONE 'UTC'",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply_to", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("price_kwh", sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mrid"),
    )
    op.create_index(
        op.f("ix_csipaus_dynamic_price_finished_at"), "csipaus_dynamic_price", ["finished_at"], unique=False
    )
    op.create_table(
        "ocpp_metadata",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("max_voltage_volts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("min_voltage_volts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_power_watts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_charge_rate_watts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("max_discharge_rate_watts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("set_grad_w", sa.DOUBLE_PRECISION(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ocpp_metadata_created_at"), "ocpp_metadata", ["created_at"], unique=False)
    op.create_table(
        "ocpp_reading",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("reading_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("frequency_hz", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("import_active_power_watts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("export_active_power_watts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("import_reactive_power_var", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("export_reactive_power_var", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("soc_percent", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("voltage_volts", sa.DOUBLE_PRECISION(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ocpp_reading_reading_start"), "ocpp_reading", ["reading_start"], unique=False)
    op.create_table(
        "csipaus_control_response",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("csipaus_control_id", sa.BIGINT(), nullable=False),
        sa.Column("response_status", sa.INTEGER(), nullable=False),
        sa.Column("end_device_lfdi", sa.String(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["csipaus_control_id"],
            ["csipaus_control.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "csipaus_control_id",
            "end_device_lfdi",
            "response_status",
            name="uc_csipaus_control_response_control_device_status",
        ),
    )
    op.create_index(
        "idx_unsent_responses",
        "csipaus_control_response",
        ["not_before"],
        unique=False,
        postgresql_where=sa.text("sent_at IS NULL"),
    )
    op.create_index(
        op.f("ix_csipaus_control_response_csipaus_control_id"),
        "csipaus_control_response",
        ["csipaus_control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_csipaus_control_response_not_before"), "csipaus_control_response", ["not_before"], unique=False
    )
    op.create_table(
        "csipaus_dynamic_price_response",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("csipaus_dynamic_price_id", sa.BIGINT(), nullable=False),
        sa.Column("response_status", sa.INTEGER(), nullable=False),
        sa.Column("end_device_lfdi", sa.String(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["csipaus_dynamic_price_id"],
            ["csipaus_dynamic_price.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "csipaus_dynamic_price_id",
            "end_device_lfdi",
            "response_status",
            name="uc_csipaus_dynamic_price_response_device_status",
        ),
    )
    op.create_index(
        "idx_unsent_dynamic_price_responses",
        "csipaus_dynamic_price_response",
        ["not_before"],
        unique=False,
        postgresql_where=sa.text("sent_at IS NULL"),
    )
    op.create_index(
        op.f("ix_csipaus_dynamic_price_response_csipaus_dynamic_price_id"),
        "csipaus_dynamic_price_response",
        ["csipaus_dynamic_price_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_csipaus_dynamic_price_response_not_before"),
        "csipaus_dynamic_price_response",
        ["not_before"],
        unique=False,
    )
    op.create_table(
        "troca_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("basic_user", sa.String(), nullable=False),
        sa.Column("basic_password", sa.String(), nullable=False),
        sa.Column("connector_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_troca_config_created_at"), "troca_config", ["created_at"], unique=False)
    op.create_table(
        "satec_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("poll_rate_seconds", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=True),
        sa.Column("port", sa.String(), nullable=True),
        sa.Column("port_tcp", sa.Integer(), server_default="502", nullable=False),
        sa.Column("unit", sa.Integer(), server_default="1", nullable=False),
        sa.Column("baud", sa.Integer(), server_default="19200", nullable=False),
        sa.Column("parity", sa.String(), server_default="N", nullable=False),
        sa.Column("timeout_seconds", sa.DOUBLE_PRECISION(), server_default="1.0", nullable=False),
        sa.Column("include_phases", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("include_energy", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("float_mode", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "satec_reading",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("satec_config_id", sa.Integer(), nullable=False),
        sa.Column("reading_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("total_kw", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_kvar", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_kva", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_pf", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_pf_lag", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_pf_lead", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("kw_import", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("kw_export", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("kvar_import", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("kvar_export", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("v_avg_ln", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("v_avg_ll", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("i_avg", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("frequency", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("frequency_mhz", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("i_neutral", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("v_unbalance", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("i_unbalance", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("v1", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("v2", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("v3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("i1", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("i2", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("i3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kw_l1", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kw_l2", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kw_l3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kvar_l1", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kvar_l2", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kvar_l3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kva_l1", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kva_l2", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("kva_l3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("pf_l1", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("pf_l2", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("pf_l3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.ForeignKeyConstraint(
            ["satec_config_id"],
            ["satec_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "satec_config_id_reading_start_idx", "satec_reading", ["satec_config_id", "reading_start"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("satec_config_id_reading_start_idx", table_name="satec_reading")
    op.drop_table("satec_reading")
    op.drop_table("satec_config")
    op.drop_index(op.f("ix_troca_config_created_at"), table_name="troca_config")
    op.drop_table("troca_config")
    op.drop_index(op.f("ix_csipaus_dynamic_price_response_not_before"), table_name="csipaus_dynamic_price_response")
    op.drop_index(
        op.f("ix_csipaus_dynamic_price_response_csipaus_dynamic_price_id"), table_name="csipaus_dynamic_price_response"
    )
    op.drop_index(
        "idx_unsent_dynamic_price_responses",
        table_name="csipaus_dynamic_price_response",
        postgresql_where=sa.text("sent_at IS NULL"),
    )
    op.drop_table("csipaus_dynamic_price_response")
    op.drop_index(op.f("ix_csipaus_control_response_not_before"), table_name="csipaus_control_response")
    op.drop_index(op.f("ix_csipaus_control_response_csipaus_control_id"), table_name="csipaus_control_response")
    op.drop_index(
        "idx_unsent_responses", table_name="csipaus_control_response", postgresql_where=sa.text("sent_at IS NULL")
    )
    op.drop_table("csipaus_control_response")
    op.drop_index(op.f("ix_ocpp_reading_reading_start"), table_name="ocpp_reading")
    op.drop_table("ocpp_reading")
    op.drop_index(op.f("ix_ocpp_metadata_created_at"), table_name="ocpp_metadata")
    op.drop_table("ocpp_metadata")
    op.drop_index(op.f("ix_csipaus_dynamic_price_finished_at"), table_name="csipaus_dynamic_price")
    op.drop_table("csipaus_dynamic_price")
    op.drop_table("csipaus_default")
    op.drop_index(op.f("ix_csipaus_control_finished_at"), table_name="csipaus_control")
    op.drop_table("csipaus_control")
    op.drop_index(op.f("ix_csipaus_config_created_at"), table_name="csipaus_config")
    op.drop_table("csipaus_config")
    # ### end Alembic commands ###
