"""init

Revision ID: 26fe5b9d5411
Revises:
Create Date: 2026-09-03 10:47:19.422052

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26fe5b9d5411"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "csipaus_control",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("primacy", sa.INTEGER(), nullable=False),
        sa.Column("mrid", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.INTEGER(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            sa.Computed(
                "(started_at AT TIME ZONE 'UTC' + duration_seconds * interval '1 second') AT TIME ZONE 'UTC'",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ramp_time_seconds", sa.Integer(), nullable=True),
        sa.Column("connect", sa.Boolean(), nullable=True),
        sa.Column("energize", sa.Boolean(), nullable=True),
        sa.Column("import_limit_watts", sa.Integer(), nullable=True),
        sa.Column("export_limit_watts", sa.Integer(), nullable=True),
        sa.Column("load_limit_watts", sa.Integer(), nullable=True),
        sa.Column("generation_limit_watts", sa.Integer(), nullable=True),
        sa.Column("storage_target_watts", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mrid"),
    )
    op.create_index(op.f("ix_csipaus_control_finished_at"), "csipaus_control", ["finished_at"], unique=False)
    op.create_table(
        "csipaus_default",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "active_range",
            postgresql.TSTZRANGE(),
            sa.Computed("tstzrange(started_at, finished_at, '[)')", persisted=True),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ramp_percent_max_second_hundredths", sa.Integer(), nullable=True),
        sa.Column("connect", sa.Boolean(), nullable=True),
        sa.Column("energize", sa.Boolean(), nullable=True),
        sa.Column("import_limit_watts", sa.Integer(), nullable=True),
        sa.Column("export_limit_watts", sa.Integer(), nullable=True),
        sa.Column("load_limit_watts", sa.Integer(), nullable=True),
        sa.Column("generation_limit_watts", sa.Integer(), nullable=True),
        sa.Column("storage_target_watts", sa.Integer(), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("active_range"), "&&"), using="gist", name="excl_csipaus_default_active_range_overlap"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meter",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "csipaus_control_response",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("csipaus_control_id", sa.Integer(), nullable=False),
        sa.Column("response_status", sa.INTEGER(), nullable=False),
        sa.Column("end_device_mrid", sa.String(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["csipaus_control_id"],
            ["csipaus_control.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "csipaus_control_id",
            "end_device_mrid",
            "response_status",
            name="uc_csipaus_control_response_control_device_status",
        ),
    )
    op.create_index(
        "idx_unsent_responses",
        "csipaus_control_response",
        ["not_before"],
        unique=False,
        postgresql_where=sa.text("sent_at IS NULL"),
    )
    op.create_index(
        op.f("ix_csipaus_control_response_csipaus_control_id"),
        "csipaus_control_response",
        ["csipaus_control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_csipaus_control_response_not_before"), "csipaus_control_response", ["not_before"], unique=False
    )
    op.create_table(
        "meter_reading",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meter_id", sa.Integer(), nullable=False),
        sa.Column("reading_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_power_watts", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("meter_id_reading_start_idx", "meter_reading", ["meter_id", "reading_start"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("meter_id_reading_start_idx", table_name="meter_reading")
    op.drop_table("meter_reading")
    op.drop_index(op.f("ix_csipaus_control_response_not_before"), table_name="csipaus_control_response")
    op.drop_index(op.f("ix_csipaus_control_response_csipaus_control_id"), table_name="csipaus_control_response")
    op.drop_index(
        "idx_unsent_responses", table_name="csipaus_control_response", postgresql_where=sa.text("sent_at IS NULL")
    )
    op.drop_table("csipaus_control_response")
    op.drop_table("meter")
    op.drop_table("csipaus_default")
    op.drop_index(op.f("ix_csipaus_control_finished_at"), table_name="csipaus_control")
    op.drop_table("csipaus_control")
    # ### end Alembic commands ###
