"""add task health

Revision ID: c04a992df0d5
Revises: 2314e3ad8f1e
Create Date: 2026-09-23 12:16:30.244351

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c04a992df0d5"
down_revision: str | Sequence[str] | None = "2314e3ad8f1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_health",
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_exception_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_exception", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("task_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_health")
    # ### end Alembic commands ###
